# Generated by Django 5.0.4 on 2024-04-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
    ]
