# Generated by Django 5.0.4 on 2024-04-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_fluxocategoria_fluxofavorecido_fluxoformapagamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxocaixa',
            old_name='situacao',
            new_name='pago',
        ),
    ]
